# Generated by Django 5.1.4 on 2024-12-11 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0003_clientdiet_clientgrocerylist_clientmeal_and_more'),
        ('mealplanning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('number_of_saves', models.PositiveIntegerField(default=0)),
                ('up_votes', models.PositiveIntegerField(default=0)),
                ('down_votes', models.PositiveIntegerField(default=0)),
                ('comments', models.TextField(blank=True, null=True)),
                ('video', models.URLField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_meals', to='mealplanning.mealcategory')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_variants', to='mealplanning.meal')),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_meals', to='client.client')),
            ],
        ),
        migrations.CreateModel(
            name='SharedRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('number_of_saves', models.PositiveIntegerField(default=0)),
                ('up_votes', models.PositiveIntegerField(default=0)),
                ('down_votes', models.PositiveIntegerField(default=0)),
                ('comments', models.TextField(blank=True, null=True)),
                ('video', models.URLField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_recipes', to='mealplanning.recipecategory')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_variants', to='mealplanning.recipe')),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_recipes', to='client.client')),
            ],
        ),
    ]
