# Generated by Django 5.1.4 on 2024-12-11 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_clientdiet_clientgrocerylist_clientmeal_and_more'),
        ('mealplanning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdiet',
            name='allergies',
            field=models.ManyToManyField(blank=True, related_name='clients', to='mealplanning.allergen'),
        ),
        migrations.AddField(
            model_name='clientdiet',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diet_restrictions', to='client.client'),
        ),
        migrations.AddField(
            model_name='clientgrocerylist',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grocery_lists', to='client.client'),
        ),
        migrations.AddField(
            model_name='clientgrocerylist',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='grocery_lists', to='mealplanning.groceryitem'),
        ),
        migrations.AddField(
            model_name='clientmeal',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_meals', to='client.client'),
        ),
        migrations.AddField(
            model_name='clientmeal',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_clients', to='mealplanning.meal'),
        ),
        migrations.AddField(
            model_name='clientmealschedule',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meal_schedule', to='client.client'),
        ),
        migrations.AddField(
            model_name='clientmealschedule',
            name='plans',
            field=models.ManyToManyField(blank=True, related_name='client_schedules', to='mealplanning.weekplan'),
        ),
        migrations.AddField(
            model_name='clientrecipe',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_recipes', to='client.client'),
        ),
        migrations.AddField(
            model_name='clientrecipe',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_clients', to='mealplanning.recipe'),
        ),
    ]
