name: Build and deploy Python app to Azure Web App - kobrabites-backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create and start virtual environment
        run: |
          cd ./kobrabitescore
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          cd ./kobrabitescore
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Collect static files
        run: |
          cd ./kobrabitescore
          source venv/bin/activate
          python manage.py collectstatic --noinput

      - name: Zip artifact for deployment
        run: |
          zip release.zip ./kobrabitescore -r -x "./kobrabitescore/venv/*"

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: Production
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip ./release.zip

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create and start virtual environment
        run: |
          cd ./kobrabitescore
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C9DCA6520ACC47FE9925B8064911805F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F0D3D34996B540539BF39BB1759CB5C5 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_1BC6532CCD27492589A64D394ADFA738 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'kobrabites-backend'
          slot-name: 'Production'
          package: ./kobrabitescore

      - name: Run migrations and collectstatic
        run: |
          cd ./kobrabitescore
          source venv/bin/activate
          python manage.py migrate
          python manage.py collectstatic --noinput
        env:
          DJANGO_SETTINGS_MODULE: kobrabitescore.settings
          DJANGO_SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DJANGO_DEBUG: ${{ secrets.DEBUG }}
          DJANGO_ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASS }}
          DB_SERVER: ${{ secrets.DB_HOST }}
          DB_DATABASE: ${{ secrets.DB_NAME }}
          DB_PORT: ${{ secrets.DB_PORT }}
