name: Build and deploy Python app to Azure Web App

env:
  AZURE_WEBAPP_NAME: kobrabites-backend  # Set this to the name of your Azure Web App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - uses: actions/checkout@v4

      # Step 2: Set up Python version
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # Step 3: Create and activate virtual environment
      - name: Create and activate virtual environment
        run: |
          cd kobrabitescore
          python -m venv venv
          source venv/bin/activate

      # Step 4: Install dependencies
      - name: Install dependencies
        run: |
          cd kobrabitescore
          python -m pip install --upgrade pip
          pip install -r requirements.txt

     
      # Step 6: Zip artifact for deployment
      - name: Zip artifact for deployment
        run: |
          zip -r release.zip ./kobrabitescore -x "venv/*" "*.git/*" "*.github/*" "*.DS_Store"

       # Step 5: Collect static files (if applicable)
      - name: Collect static files
        run: |
          cd kobrabitescore
          python manage.py collectstatic --noinput

      # Step 7: Upload artifact for deployment
      # Step 6: Zip artifact for deployment
      - name: Zip artifact for deployment
        run: zip -r python-app.zip ./kobrabitescore -x "venv/*" "*.git/*" "*.github/*" "*.DS_Store"
      
      # Step 7: Upload artifact for deployment
      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: python-app.zip


  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
  
    steps:
      # Step 1: Download artifact from the build job
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app
  
      # Step 2: Unzip artifact for deployment
      - name: Unzip artifact
        run: |
          unzip -o python-app.zip -d deployment-folder
  
      # Step 3: Deploy to Azure Web App
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: './deployment-folder'

