name: Build and deploy Flutter web app to Azure Web App - kobrabites-frontend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.0'

      - name: Get dependencies
        run: flutter pub get

      - name: Build for web
        run: flutter build web

      - name: Prepare for deployment
        run: |
          cd ./kobrabites
          mkdir wwwroot
          cp -r build/web/* wwwroot/
          cp server.js wwwroot/

      - name: Zip artifact for deployment
        run: zip release.zip ./kobrabites -r -x "venv/*"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: ./release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: Production
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip ./release.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6665600E55F54153B7BD0B5C27440DFD }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_955209A1E32947A69B78E4E123D2382B }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_0F1261F942B24A59BF2D275F9EC83F20 }}


      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'kobrabites'
          slot-name: 'Production'
          package: ./kobrabites
